In [1]:
!python -m pip install numpy

In [4]:
import numpy as np

A = np.array([
    [2,3,3], 
    [5,3,1], 
    [4,5,1]
])
U, S, V = np.linalg.svd(A)

In [9]:
print(U.shape, S.shape, V.shape)
print(U)
print(S)
print(V)

(3, 3) (3,) (3, 3)
[[-0.44055623  0.85416795 -0.2762378 ]
 [-0.59895345 -0.50888162 -0.61829949]
 [-0.66870394 -0.10694211  0.73579781]]
[9.55899032 2.37444865 1.40985736]
[[-0.68529157 -0.67601792 -0.27087862]
 [-0.53226699  0.21105886  0.81984511]
 [-0.49705866  0.70601269 -0.50445889]]


In [8]:

print(A)
print(np.dot(U*S, V))

print("Is A == USV? ", np.allclose(A, np.dot(U * S, V)))

[[2 3 3]
 [5 3 1]
 [4 5 1]]
[[2. 3. 3.]
 [5. 3. 1.]
 [4. 5. 1.]]
Is A == USV?  True
